// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0DI_rkSCkiUbBUWGq2J6b6tAN0eS2U0o',
    appId: '1:545535659652:web:693fe8a1b5b8cfeb717cd1',
    messagingSenderId: '545535659652',
    projectId: 'ecampus-21f18',
    authDomain: 'ecampus-21f18.firebaseapp.com',
    databaseURL: 'https://ecampus-21f18.firebaseio.com',
    storageBucket: 'ecampus-21f18.appspot.com',
    measurementId: 'G-2HMV9DVXGS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1GTuUuahvxULyxXPdTlCKa1I0D6s-_3g',
    appId: '1:545535659652:android:7ea5ed969baff1b8717cd1',
    messagingSenderId: '545535659652',
    projectId: 'ecampus-21f18',
    databaseURL: 'https://ecampus-21f18.firebaseio.com',
    storageBucket: 'ecampus-21f18.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgyxuAucWzsJHWlEOtd-7LMjGt6GTTjVE',
    appId: '1:545535659652:ios:40988b762454623a717cd1',
    messagingSenderId: '545535659652',
    projectId: 'ecampus-21f18',
    databaseURL: 'https://ecampus-21f18.firebaseio.com',
    storageBucket: 'ecampus-21f18.appspot.com',
    androidClientId: '545535659652-sibfmflh7pfn7ibtbjs7c0psdnlf7td9.apps.googleusercontent.com',
    iosClientId: '545535659652-u3m0fe9d221vkkkrklnk4g2kforufmmj.apps.googleusercontent.com',
    iosBundleId: 'uz.mq.ecampus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgyxuAucWzsJHWlEOtd-7LMjGt6GTTjVE',
    appId: '1:545535659652:ios:94b0c8a7a770eb58717cd1',
    messagingSenderId: '545535659652',
    projectId: 'ecampus-21f18',
    databaseURL: 'https://ecampus-21f18.firebaseio.com',
    storageBucket: 'ecampus-21f18.appspot.com',
    androidClientId: '545535659652-sibfmflh7pfn7ibtbjs7c0psdnlf7td9.apps.googleusercontent.com',
    iosClientId: '545535659652-fofeaegcshb5tbgovps4jto638c98fb8.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecampusNcfu',
  );
}
